services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres          # match spring.datasource.url (database name)
      POSTGRES_USER: postgres        # match spring.datasource.username
      POSTGRES_PASSWORD: 123456      # match spring.datasource.password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    container_name: tech-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: techPractica

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    container_name: tech-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:

