# GitHub Actions CI/CD Pipeline
name: CI/CD Pipeline

# Trigger the workflow on pull requests to main branch or commits to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Set up Java for backend
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
   
    
    # Cache Gradle dependencies for faster builds
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    # Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x ./backend/gradlew
      
    # Build backend
    - name: Build backend with Gradle
      run: |
        cd backend
        ./gradlew build -x test
    
    # Run specific unit tests
 # - name: Run User Application tests
 #   run: |
    #   cd backend
     #  ./gradlew test --tests "com.spring.techpractica.Application.User.*"
    
    # Install frontend dependencies
   
